# Generated by Django 4.1.13 on 2024-06-12 11:48

from django.db import migrations, models
import generic_app.generic_models.fields.XLSX_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationIDs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context_id', models.TextField(default='test_id')),
                ('calculation_record', models.TextField()),
                ('calculation_id', models.TextField(default='test_id')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('trigger_name', models.TextField(null=True)),
                ('message_type', models.TextField(default='')),
                ('calculationId', models.TextField(default='test_id')),
                ('calculation_record', models.TextField(default='legacy')),
                ('message', models.TextField()),
                ('method', models.TextField()),
                ('is_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.TextField(null=True)),
                ('logfile', generic_app.generic_models.fields.XLSX_field.XLSXField(default='', max_length=300, upload_to='')),
                ('input_validation', generic_app.generic_models.fields.XLSX_field.XLSXField(default='', max_length=300, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationRestrictedModelExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('traceback', models.TextField(default='', null=True)),
                ('calculationId', models.TextField(default='-1')),
                ('calculation_record', models.TextField(default='legacy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('group',), name='defining_fields_Log'),
        ),
    ]
