name: Draft a Release

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false
        description: Ref for the commit you would like to release. Only provide this if the commit is not the latest in the branch.
        default: ""
      increment:
        type: choice
        options:
          - patch
          - minor
          - major
        default: minor

jobs:
  release:
    uses: LundIT/instance-controller-deployment/.github/workflows/generic-release.yaml@develop
    with:
      ref: ${{ inputs.ref}}
      increment: ${{ inputs.increment }}
    secrets: inherit

  build-and-deploy:
    needs: [release]
    uses: LundIT/lex-app/.github/workflows/draft-release.yaml@main
    with:
      increment: major
    secrets: inherit