name: ScanCode Toolkit Scan

on:
  schedule:
    - cron: "0 23 * * 0" # scheduled to run every Sunday at 23:00 PM
  workflow_dispatch: # allows the workflow to be triggered manually

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.8 and distutils
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo add-apt-repository ppa:deadsnakes/ppa --yes
          sudo apt-get install python3.8 python3.8-distutils -y

      - name: Install ScanCode Toolkit
        run: |
          python3.8 -m pip install --upgrade pip
          python3.8 -m pip install scancode-toolkit

      - name: Scan code and print results
        run: |
          scancode -clip --json-pp - .
