name: Update Lex-App on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  update-dependency-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lex-app
        uses: actions/checkout@v3
        with:
          repository: 'LundIT/lex-app'
          token: ${{ secrets.PAT }}
          path: 'lex-app'

      - name: Extract Version Tag
        id: version_tag
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          echo "VERSION_TAG=$VERSION_TAG"
          echo "::set-output name=version::$VERSION_TAG"
        shell: bash

      - name: Update requirements.txt in lex-app
        run: |
          sed -i 's|generic_app @ git+https://github.com/LundIT/lex-generic-app.*|generic_app @ git+https://github.com/LundIT/lex-generic-app@${{ steps.version_tag.outputs.version }}|' requirements.txt
          cat requirements.txt
        shell: bash
        working-directory: ./lex-app

      - name: Setup Git Config
        run: |
          git config user.name '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.email 'github-actions[bot]'
        working-directory: ./lex-app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update generic_app dependency to ${{ steps.version_tag.outputs.version }}"
          branch: "update-dependency-${{ steps.version_tag.outputs.version }}"  # This is the branch where changes are committed
          title: "Update generic_app to ${{ steps.version_tag.outputs.version }}"
          body: |
            This is an automated pull request to update the lex-generic-app dependency to the latest version.
            
            **Changes:**
            - Updated `lex-generic-app` to version `${{ steps.version_tag.outputs.version }}`.
          base: 'main'
          path: './lex-app'
          
