name: Update Lex-App on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  update-dependency-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lex-app
        uses: actions/checkout@v3
        with:
          repository: 'LundIT/lex-app'
          token: ${{ secrets.PAT }}
          path: 'lex-app'

      - name: Extract Version Tag
        id: version_tag
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          echo "VERSION_TAG=$VERSION_TAG"
          echo "::set-output name=version::$VERSION_TAG"
        shell: bash

      - name: Update requirements.txt in lex-app
        run: |
          echo "Before sed:"
          cat requirements.txt
          sed -i "s|generic_app @ git+https://github.com/LundIT/lex-generic-app@\([^@]*\)|generic_app @ git+https://github.com/LundIT/lex-generic-app@${{ steps.version_tag.outputs.version }}|" requirements.txt
          echo "After sed:"
          cat requirements.txt
        shell: bash
        working-directory: ./lex-app

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi
        working-directory: ./lex-app

      - name: Setup Git Config
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.email 'github-actions[bot]'
        working-directory: ./lex-app

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git checkout -b update-dependency-${{ steps.version_tag.outputs.version }}
          git add requirements.txt
          git commit -m "Update generic_app dependency to ${{ steps.version_tag.outputs.version }}"
          git push origin update-dependency-${{ steps.version_tag.outputs.version }}
        working-directory: ./lex-app
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.PAT }}

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update generic_app dependency to ${{ steps.version_tag.outputs.version }}"
          branch: "update-dependency-${{ steps.version_tag.outputs.version }}"
          title: "Update generic_app to ${{ steps.version_tag.outputs.version }}"
          body: "Automated update to the latest version of generic_app"
          base: 'main'
          path: './lex-app'
          repo: 'LundIT/lex-app'
